version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: sweet-shop-db
    environment:
      POSTGRES_DB: sweet_shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: ./backend
    container_name: sweet-shop-backend
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-password123}@database:5432/sweet_shop_db?schema=public
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      JWT_EXPIRES_IN: 7d
      PORT: 3001
      NODE_ENV: production
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm start"

  # Frontend
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:3001/api}
    container_name: sweet-shop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: